### ISSUE TITLE
Error while using Backtesting.py

### ISSUE THREAD

**Issue by Nitin365-ai** [ChadThackray/WFO-backtesting-py-2022#1]
i am trying to backtest simple stochastic strategy in Backtesting.py but i am getting following error.
**ValueError: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (116051,); indicator "stoch(14,3)"shape: (2, 116038)** 
I am unable to sort out cause of error. please help me out.
my code is as follows'

import pandas as pd
import pandas_ta as ta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover, resample_apply

data = pd.read_csv(r'F:\Algo Trading\Angel One\Nifty\1 Min\Nifty 1 Min Data _1 Min.csv', parse_dates = ['Date'],index_col = 'Date' )

class stoch(Strategy):
    n1 = 100
    k = 14
    d = 3
    
    def init(self):
        
        self.ema_100 = self.I(ta.ema, pd.Series(self.data.Close), length=self.n1)
        self.stoch = self.I(ta.stoch, pd.Series(self.data.High), pd.Series(self.data.Low), pd.Series(self.data.Close), k=self.k, d=self.d)
                            
    def next(self):
        
        stoch_k = self.stoch[0]
        stoch_d = self.stoch[1]
                            
        if self.data.Close > self.ema_100 and crossover(stoch_k, stoch_d):
            self.buy(size = 1)
            
        if self.position.is_long and crossover(stoch_d, stoch_k) :
            self.position.close()

bt = Backtest(data,stoch,cash=100000)
stats = bt.run()
stats

**Comment by ChadThackray** [comment]
Hi, this is unrelated to the code in the repo so I'm going to close this issue
